var D=document,$=D.getElementById.bind(D),E=encodeURIComponent,P="/",L=[];
function T(){var m=D.querySelector('meta[name="csrf-token"]');return m?m.content:""}
function N(p){return!p||p[0]!=="/"?"/":p.length>1&&p[p.length-1]==="/"?p.slice(0,-1):p}
function U(p){p=N(p);if(p==="/")return null;var i=p.lastIndexOf("/");return i<=0?"/":p.slice(0,i)}
function J(n){return P==="/"?"/"+n:P+"/"+n}
function S(t,ok){var x=$("status");x.textContent=t;x.className="status-pill "+(ok?"status-ok":"status-bad")}
function O(t,p){var x=$("drop");if(t)$("drop-sub").textContent=t;if(typeof p==="number")$("drop-bar").style.width=p+"%";x.classList.add("show")}
function O0(){$("drop").classList.remove("show");$("drop-sub").textContent="Release";$("drop-bar").style.width="0%"}
function B(){var b=$("breadcrumb");b.innerHTML="";var r=D.createElement("span");r.className="crumb";r.textContent="Root";r.setAttribute("data-path","/");r.onclick=function(){L0("/")};b.appendChild(r);var parts=N(P).split("/"),a="";for(var i=0;i<parts.length;i++){var p=parts[i];if(!p)continue;a+="/"+p;var it=D.createElement("span");it.className="crumb";it.textContent=p;it.setAttribute("data-path",a);it.onclick=function(){L0(this.getAttribute("data-path"))};b.appendChild(it)}}
function R(q){var fl=$("file-list");fl.innerHTML="";q=(q||"").trim().toLowerCase();var a=L||[],k=0;if(!a.length){fl.innerHTML='<div class="empty">Empty</div>';return}for(var i=0;i<a.length;i++){var x=a[i];if(q&&x.name.toLowerCase().indexOf(q)<0)continue;k++;var dir=x.type==="directory",path=J(x.name),ic=dir?"📁":"📄";var c=D.createElement("div");c.className="card";c.setAttribute("data-path",path);c.setAttribute("data-dir",dir?"1":"0");c.onclick=function(){var p=this.getAttribute("data-path");if(this.getAttribute("data-dir")==="1")L0(p);else location.href="/api/download?path="+E(p)};c.innerHTML='<div class="icon">'+ic+'</div><div class="meta"><div class="name">'+x.name+'</div></div>';fl.appendChild(c)}if(!k)fl.innerHTML='<div class="empty">Empty</div>'}
function L0(path){P=N(path);$("current-path").textContent=P;$("file-list").innerHTML='<div class="loading">Loading...</div>';fetch("/api/list?path="+E(P)).then(function(r){if(!r.ok)throw new Error("HTTP "+r.status);return r.json()}).then(function(d){L=d&&d.entries?d.entries:[];B();R($("search").value);S("Connected",1)}).catch(function(){ $("file-list").innerHTML='<div class="error">Error</div>';S("Error",0)})}
function U0(files){if(!files||!files.length)return;var i=0;function n(){if(i>=files.length){O0();L0(P);return}var f=files[i++];S("Upload",0);O("Uploading",0);var x=new XMLHttpRequest();x.open("POST","/api/upload?path="+E(P)+"&name="+E(f.name),1);var t=T();if(t)x.setRequestHeader("X-CSRF-Token",t);x.upload.onprogress=function(e){if(e.lengthComputable)O("Uploading",Math.floor(e.loaded/e.total*100))};x.onload=function(){x.status>=200&&x.status<300?n():(S("Error",0),setTimeout(O0,800))};x.onerror=function(){S("Error",0);setTimeout(O0,800)};x.send(f)}n()}
function C0(){var name=prompt("File name");if(!name)return;S("Creating...",0);fetch("/api/create_file?path="+E(P)+"&name="+E(name),{method:"POST",headers:{"Content-Type":"text/plain","X-CSRF-Token":T()},body:""}).then(function(r){if(!r.ok)throw new Error("HTTP "+r.status);return r.json()}).then(function(){L0(P)}).catch(function(e){S("Error",0);alert("Failed: "+e.message)})}
D.addEventListener("DOMContentLoaded",function(){$("btn-up").onclick=function(){var p=U(P);if(p!==null)L0(p)};$("btn-refresh").onclick=function(){L0(P)};$("search").oninput=function(){R(this.value)};$("btn-upload").onclick=function(){$("file-input").click()};$("file-input").onchange=function(e){U0(e.target.files);e.target.value=""};$("btn-create").onclick=function(){C0()};var dr=0;D.addEventListener("dragenter",function(e){e.preventDefault();dr++;O()});D.addEventListener("dragover",function(e){e.preventDefault();O()});D.addEventListener("dragleave",function(e){e.preventDefault();dr=Math.max(0,dr-1);if(dr===0)O0()});D.addEventListener("drop",function(e){e.preventDefault();dr=0;O("Upload",0);U0(e.dataTransfer.files)});L0("/")});
